import * as fs from 'fs';
import * as path from 'path';
import { migrate } from '@/db/schema';
import { createMemoryDriver } from '../../../test/memoryDriver';

const FILE = path.resolve(__dirname, '../schema.sql');

async function dump(): Promise<string> {
  const db = createMemoryDriver();
  await migrate(db);
  const [{ version }] = (await db.all<{ version: number }>('SELECT version FROM schema_version')) as [{ version: number }];
  const rows = await db.all<{ sql: string }>(
    "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY type, name",
  );
  return [
    '-- GENERATED by shared/schema/__tests__/schema.test.ts (npm run fixtures:record) — do not edit.',
    '-- The schema after every migration in src/db/schema.ts. Iris I4 must reproduce it.',
    `-- schema_version: ${version}`,
    '',
    rows.map((r) => `${r.sql.trim()};`).join('\n\n'),
    '',
  ].join('\n');
}

test(process.env.RECORD_FIXTURES === '1' ? 'records shared/schema/schema.sql' : 'matches shared/schema/schema.sql (re-run `npm run fixtures:record` after a migration)', async () => {
  const actual = await dump();
  if (process.env.RECORD_FIXTURES === '1') {
    fs.writeFileSync(FILE, actual);
    return;
  }
  expect(fs.existsSync(FILE)).toBe(true);
  expect(fs.readFileSync(FILE, 'utf8')).toBe(actual);
});

test('the snapshot is at the schema version the Swift side targets', async () => {
  expect(await dump()).toContain('-- schema_version: 10');
});
