import * as fs from 'fs';
import * as path from 'path';
import { MIGRATIONS, migrate } from '@/db/schema';
import { createMemoryDriver } from '../../../test/memoryDriver';

const FILE = path.resolve(__dirname, '../schema.sql');

async function dump(): Promise<string> {
  const db = createMemoryDriver();
  await migrate(db);
  const [{ version }] = (await db.all<{ version: number }>('SELECT version FROM schema_version')) as [{ version: number }];
  const rows = await db.all<{ sql: string }>(
    "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY type, name",
  );
  return [
    '-- GENERATED by shared/schema/__tests__/schema.test.ts (npm run fixtures:record) — do not edit.',
    '-- The schema after every migration in src/db/schema.ts. Iris I4 must reproduce it.',
    `-- schema_version: ${version}`,
    '',
    rows.map((r) => `${r.sql.trim()};`).join('\n\n'),
    '',
  ].join('\n');
}

test(process.env.RECORD_FIXTURES === '1' ? 'records shared/schema/schema.sql' : 'matches shared/schema/schema.sql (re-run `npm run fixtures:record` after a migration)', async () => {
  const actual = await dump();
  if (process.env.RECORD_FIXTURES === '1') {
    fs.writeFileSync(FILE, actual);
    return;
  }
  expect(fs.existsSync(FILE)).toBe(true);
  expect(fs.readFileSync(FILE, 'utf8')).toBe(actual);
});

test('the snapshot is at the schema version the Swift side targets', async () => {
  expect(await dump()).toContain('-- schema_version: 10');
});

const SWIFT_MIGRATIONS = path.resolve(__dirname, '../../../apple/IrisCore/Sources/IrisCore/Persistence/Migrations.generated.swift');

/** A Swift string literal holding `s` exactly. */
function swiftLiteral(s: string): string {
  return `"${s.replace(/[\\"\n\r\t]|[\u0000-\u001f]/g, (c) =>
    c === '\\' ? '\\\\' : c === '"' ? '\\"' : c === '\n' ? '\\n' : c === '\r' ? '\\r' : c === '\t' ? '\\t' : `\\u{${c.charCodeAt(0).toString(16)}}`,
  )}"`;
}

function swiftMigrations(): string {
  return [
    '// GENERATED by shared/schema/__tests__/schema.test.ts (npm run fixtures:record) — do not edit.',
    '// The migrations in src/db/schema.ts, verbatim: SQLite stores each CREATE statement\'s',
    '// text, so shared/schema/schema.sql only matches when these exact strings run (Iris I4).',
    '',
    'let migrations: [String] = [',
    ...MIGRATIONS.map((m) => `    ${swiftLiteral(m)},`),
    ']',
    '',
  ].join('\n');
}

test(process.env.RECORD_FIXTURES === '1' ? 'records the Swift migrations' : 'the Swift migrations match src/db/schema.ts (re-run `npm run fixtures:record`)', () => {
  if (process.env.RECORD_FIXTURES === '1') {
    fs.mkdirSync(path.dirname(SWIFT_MIGRATIONS), { recursive: true });
    fs.writeFileSync(SWIFT_MIGRATIONS, swiftMigrations());
    return;
  }
  expect(fs.readFileSync(SWIFT_MIGRATIONS, 'utf8')).toBe(swiftMigrations());
});
