-- GENERATED by shared/schema/__tests__/schema.test.ts (npm run fixtures:record) — do not edit.
-- The schema after every migration in src/db/schema.ts. Iris I4 must reproduce it.
-- schema_version: 10

CREATE INDEX idx_entry_series ON entry(series_id);

CREATE INDEX idx_entry_status ON entry(status);

CREATE INDEX idx_rating_category ON rating(category, position);

CREATE TABLE app_meta (
    key   TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL
  );

CREATE TABLE "entry" (
    id              TEXT PRIMARY KEY NOT NULL,
    series_id       TEXT REFERENCES series(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    ordinal         INTEGER,
    media_type      TEXT NOT NULL CHECK (media_type IN ('episode','issue','volume','book','movie','comic')),
    status          TEXT NOT NULL CHECK (status IN ('unstarted','in_progress','done')),
    started_at      TEXT,
    finished_at     TEXT,
    created_at      TEXT NOT NULL,
    paused          INTEGER NOT NULL DEFAULT 0,
    external_source TEXT,
    external_id     TEXT
  , cover_url TEXT, creator TEXT, description TEXT, release_year TEXT, metadata_checked_at TEXT, genres_json TEXT);

CREATE TABLE rating (
    track_kind TEXT NOT NULL CHECK (track_kind IN ('series','entry')),
    track_id   TEXT NOT NULL,
    category   TEXT NOT NULL CHECK (category IN ('show','movie','book','comic','manga')),
    sentiment  TEXT NOT NULL CHECK (sentiment IN ('liked','fine','disliked')),
    position   INTEGER NOT NULL,
    rated_at   TEXT NOT NULL,
    PRIMARY KEY (track_kind, track_id)
  );

CREATE TABLE schema_version (version INTEGER NOT NULL);

CREATE TABLE series (
    id              TEXT PRIMARY KEY NOT NULL,
    title           TEXT NOT NULL,
    media_type      TEXT NOT NULL CHECK (media_type IN ('show','comic','manga')),
    unit_label      TEXT NOT NULL CHECK (unit_label IN ('episode','issue','volume')),
    created_at      TEXT NOT NULL,
    external_source TEXT,
    external_id     TEXT
  , ongoing INTEGER NOT NULL DEFAULT 0, paused INTEGER NOT NULL DEFAULT 0, seasons_json TEXT, cover_url TEXT, creator TEXT, description TEXT, release_year TEXT, metadata_checked_at TEXT, genres_json TEXT);
