// GENERATED by scripts/iris-tokens.js from design/iris/tokens.json — do not edit; run `npm run tokens`.
// source-sha256: 202475f418ce871cfaf96919cb746ae9ffc8f1176ed2097af8eaa9237babbdf7

import SwiftUI
import UIKit

/// Iris design tokens (spec §4.1). Edit design/iris/tokens.json, then `npm run tokens`.
enum IrisTokens {
    static let sourceSHA256 = "202475f418ce871cfaf96919cb746ae9ffc8f1176ed2097af8eaa9237babbdf7"

    enum Colors {
        static let background = Color(uiColor: .systemBackground)
        static let groupedBackground = Color(uiColor: .systemGroupedBackground)
        static let secondaryGroupedBackground = Color(uiColor: .secondarySystemGroupedBackground)
        static let label = Color(uiColor: .label)
        static let secondaryLabel = Color(uiColor: .secondaryLabel)
        static let tertiaryLabel = Color(uiColor: .tertiaryLabel)
        static let separator = Color(uiColor: .separator)
        static let fill = Color(uiColor: .systemFill)
        static let accent = Color(uiColor: .systemBlue)
        static let accentFill = dynamic((0x0071E3, 1.0), (0x0066CC, 1.0))
        static let onAccent = dynamic((0xFFFFFF, 1.0), (0xFFFFFF, 1.0))
        static let destructive = Color(uiColor: .systemRed)
        static let categoryShow = Color(uiColor: .systemPurple)
        static let categoryMovie = Color(uiColor: .systemOrange)
        static let categoryBook = Color(uiColor: .systemGreen)
        static let categoryComic = Color(uiColor: .systemPink)
        static let categoryManga = Color(uiColor: .systemTeal)
    }

    struct TextStyle: Sendable {
        let font: Font
        let size: CGFloat
        let lineHeight: CGFloat
        let tracking: CGFloat
    }

    enum Typography {
        static let largeTitle = TextStyle(font: .system(.largeTitle, weight: .bold), size: 34, lineHeight: 41, tracking: 0.4)
        static let title1 = TextStyle(font: .system(.title, weight: .bold), size: 28, lineHeight: 34, tracking: 0.38)
        static let title2 = TextStyle(font: .system(.title2, weight: .bold), size: 22, lineHeight: 28, tracking: -0.26)
        static let title3 = TextStyle(font: .system(.title3, weight: .semibold), size: 20, lineHeight: 25, tracking: -0.45)
        static let headline = TextStyle(font: .system(.headline, weight: .semibold), size: 17, lineHeight: 22, tracking: -0.43)
        static let body = TextStyle(font: .system(.body, weight: .regular), size: 17, lineHeight: 22, tracking: -0.43)
        static let callout = TextStyle(font: .system(.callout, weight: .regular), size: 16, lineHeight: 21, tracking: -0.31)
        static let subheadline = TextStyle(font: .system(.subheadline, weight: .regular), size: 15, lineHeight: 20, tracking: -0.23)
        static let footnote = TextStyle(font: .system(.footnote, weight: .regular), size: 13, lineHeight: 18, tracking: -0.08)
        static let caption1 = TextStyle(font: .system(.caption, weight: .regular), size: 12, lineHeight: 16, tracking: 0)
        static let caption2 = TextStyle(font: .system(.caption2, weight: .regular), size: 11, lineHeight: 13, tracking: 0.06)
    }

    enum Space {
        static let xxs: CGFloat = 2
        static let xs: CGFloat = 4
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 20
        static let xxl: CGFloat = 24
        static let xxxl: CGFloat = 32
    }

    enum Radius {
        static let control: CGFloat = 10
        static let card: CGFloat = 20
        static let sheet: CGFloat = 32
        static let pill: CGFloat = 9999
    }

    enum Motion {
        static let snappy = Animation.spring(response: 0.3, dampingFraction: 0.85)
        static let smooth = Animation.spring(response: 0.5, dampingFraction: 1)
        static let bouncy = Animation.spring(response: 0.5, dampingFraction: 0.7)
    }

    /// Used when Liquid Glass is unavailable or Reduce Transparency is on.
    struct GlassFallback: Sendable {
        let blur: CGFloat
        let tint: Color
        let border: Color
    }

    enum Glass {
        static let regular = GlassFallback(blur: 20, tint: dynamic((0xFFFFFF, 0.702), (0x1E1E1E, 0.6)), border: dynamic((0xFFFFFF, 0.302), (0xFFFFFF, 0.122)))
        static let clear = GlassFallback(blur: 12, tint: dynamic((0xFFFFFF, 0.349), (0x1E1E1E, 0.302)), border: dynamic((0xFFFFFF, 0.251), (0xFFFFFF, 0.078)))
    }
}

/// A colour that follows the trait collection: light value, dark value.
private func dynamic(_ light: (UInt32, Double), _ dark: (UInt32, Double)) -> Color {
    Color(uiColor: UIColor { traits in
        let (rgb, alpha) = traits.userInterfaceStyle == .dark ? dark : light
        return UIColor(
            red: CGFloat((rgb >> 16) & 0xFF) / 255,
            green: CGFloat((rgb >> 8) & 0xFF) / 255,
            blue: CGFloat(rgb & 0xFF) / 255,
            alpha: alpha
        )
    })
}
