// GENERATED by scripts/iris-tokens.js from design/iris/tokens.json — do not edit; run `npm run tokens`.
// source-sha256: 202475f418ce871cfaf96919cb746ae9ffc8f1176ed2097af8eaa9237babbdf7

export const irisSourceSha256 = '202475f418ce871cfaf96919cb746ae9ffc8f1176ed2097af8eaa9237babbdf7';

export const irisColors = {
  "light": {
    "background": "#FFFFFF",
    "groupedBackground": "#F2F2F7",
    "secondaryGroupedBackground": "#FFFFFF",
    "label": "#000000",
    "secondaryLabel": "rgba(60, 60, 67, 0.6)",
    "tertiaryLabel": "rgba(60, 60, 67, 0.302)",
    "separator": "rgba(60, 60, 67, 0.122)",
    "fill": "rgba(120, 120, 128, 0.2)",
    "accent": "#0088FF",
    "accentFill": "#0071E3",
    "onAccent": "#FFFFFF",
    "destructive": "#FF383C",
    "categoryShow": "#CB30E0",
    "categoryMovie": "#FF8D28",
    "categoryBook": "#34C759",
    "categoryComic": "#FF2D55",
    "categoryManga": "#00C3D0"
  },
  "dark": {
    "background": "#000000",
    "groupedBackground": "#000000",
    "secondaryGroupedBackground": "#1C1C1E",
    "label": "#FFFFFF",
    "secondaryLabel": "rgba(235, 235, 245, 0.6)",
    "tertiaryLabel": "rgba(235, 235, 245, 0.302)",
    "separator": "rgba(84, 84, 88, 0.502)",
    "fill": "rgba(120, 120, 128, 0.361)",
    "accent": "#0091FF",
    "accentFill": "#0066CC",
    "onAccent": "#FFFFFF",
    "destructive": "#FF4245",
    "categoryShow": "#DB34F2",
    "categoryMovie": "#FF9230",
    "categoryBook": "#30D158",
    "categoryComic": "#FF375F",
    "categoryManga": "#00D2E0"
  }
} as const;

export const irisType = {
  "largeTitle": {
    "fontSize": 34,
    "lineHeight": 41,
    "fontWeight": "700",
    "letterSpacing": 0.4
  },
  "title1": {
    "fontSize": 28,
    "lineHeight": 34,
    "fontWeight": "700",
    "letterSpacing": 0.38
  },
  "title2": {
    "fontSize": 22,
    "lineHeight": 28,
    "fontWeight": "700",
    "letterSpacing": -0.26
  },
  "title3": {
    "fontSize": 20,
    "lineHeight": 25,
    "fontWeight": "600",
    "letterSpacing": -0.45
  },
  "headline": {
    "fontSize": 17,
    "lineHeight": 22,
    "fontWeight": "600",
    "letterSpacing": -0.43
  },
  "body": {
    "fontSize": 17,
    "lineHeight": 22,
    "fontWeight": "400",
    "letterSpacing": -0.43
  },
  "callout": {
    "fontSize": 16,
    "lineHeight": 21,
    "fontWeight": "400",
    "letterSpacing": -0.31
  },
  "subheadline": {
    "fontSize": 15,
    "lineHeight": 20,
    "fontWeight": "400",
    "letterSpacing": -0.23
  },
  "footnote": {
    "fontSize": 13,
    "lineHeight": 18,
    "fontWeight": "400",
    "letterSpacing": -0.08
  },
  "caption1": {
    "fontSize": 12,
    "lineHeight": 16,
    "fontWeight": "400",
    "letterSpacing": 0
  },
  "caption2": {
    "fontSize": 11,
    "lineHeight": 13,
    "fontWeight": "400",
    "letterSpacing": 0.06
  }
} as const;

export const irisSpace = {
  "xxs": 2,
  "xs": 4,
  "sm": 8,
  "md": 12,
  "lg": 16,
  "xl": 20,
  "xxl": 24,
  "xxxl": 32
} as const;

export const irisRadius = {
  "control": 10,
  "card": 20,
  "sheet": 32,
  "pill": 9999
} as const;

export const irisMotion = {
  "snappy": {
    "response": 0.3,
    "damping": 0.85
  },
  "smooth": {
    "response": 0.5,
    "damping": 1
  },
  "bouncy": {
    "response": 0.5,
    "damping": 0.7
  }
} as const;

export const irisGlass = {
  "regular": {
    "blur": 20,
    "tint": {
      "light": "rgba(255, 255, 255, 0.702)",
      "dark": "rgba(30, 30, 30, 0.6)"
    },
    "border": {
      "light": "rgba(255, 255, 255, 0.302)",
      "dark": "rgba(255, 255, 255, 0.122)"
    }
  },
  "clear": {
    "blur": 12,
    "tint": {
      "light": "rgba(255, 255, 255, 0.349)",
      "dark": "rgba(30, 30, 30, 0.302)"
    },
    "border": {
      "light": "rgba(255, 255, 255, 0.251)",
      "dark": "rgba(255, 255, 255, 0.078)"
    }
  }
} as const;
