import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

type Gen = {
  generate(raw: string): { swift: string; ts: string; css: string; html: string };
  parseColor(value: string, where: string): { r: number; g: number; b: number; alpha: number; hex: string };
  main(argv: string[], root?: string): number;
  OUTPUTS: Record<'swift' | 'ts' | 'css' | 'html', string>;
  SOURCE: string;
  COMPONENTS: string[];
};
// eslint-disable-next-line @typescript-eslint/no-require-imports
const gen: Gen = require('../iris-tokens');

/** The smallest valid token set: one of everything. */
function tiny(): Record<string, unknown> {
  return {
    color: {
      label: { light: '#000000', dark: '#FFFFFF', ios: 'label' },
      separator: { light: '#3C3C434A', dark: '#54545899' },
      categoryShow: { light: '#AF52DE', dark: '#BF5AF2' },
    },
    type: { body: { size: 17, lineHeight: 22, weight: 'regular', tracking: -0.43, ios: 'body' } },
    space: { md: 12 },
    radius: { card: 20 },
    motion: { snappy: { response: 0.3, damping: 0.85 } },
    glass: {
      regular: { blur: 20, tint: { light: '#FFFFFFB3', dark: '#1E1E1E99' }, border: { light: '#FFFFFF4D', dark: '#FFFFFF1F' } },
    },
  };
}

describe('parseColor', () => {
  test('reads #RRGGBB as opaque', () => {
    expect(gen.parseColor('#AF52DE', 'x')).toEqual({ r: 175, g: 82, b: 222, alpha: 1, hex: 'AF52DE' });
  });
  test('reads #RRGGBBAA alpha to three decimals', () => {
    expect(gen.parseColor('#3C3C4399', 'x').alpha).toBe(0.6);
  });
  test('rejects shorthand and names the token', () => {
    expect(() => gen.parseColor('#FFF', 'color.label.light')).toThrow('color.label.light: "#FFF" is not #RRGGBB or #RRGGBBAA');
  });
});

describe('generate', () => {
  const out = gen.generate(JSON.stringify(tiny()));

  test('every output carries the GENERATED header and the source hash', () => {
    const hash = require('crypto').createHash('sha256').update(JSON.stringify(tiny())).digest('hex');
    for (const text of Object.values(out)) {
      expect(text).toContain('GENERATED by scripts/iris-tokens.js');
      expect(text).toContain(hash);
    }
  });
  test('an iOS-mapped colour uses the system colour in Swift', () => {
    expect(out.swift).toContain('static let label = Color(uiColor: .label)');
  });
  test('an unmapped colour becomes a light/dark dynamic colour in Swift, alpha included', () => {
    expect(out.swift).toContain('static let separator = dynamic((0x3C3C43, 0.29), (0x545458, 0.6))');
  });
  test('CSS emits rgba for translucent colours and a dark block', () => {
    expect(out.css).toContain('--iris-color-separator: rgba(60, 60, 67, 0.29);');
    expect(out.css).toMatch(/\[data-theme="dark"\][^}]*--iris-color-label: #FFFFFF;/s);
  });
  test('TS exposes light and dark palettes', () => {
    expect(out.ts).toContain('export const irisColors =');
    expect(out.ts).toContain('"categoryShow": "#BF5AF2"');
  });
  test('type weights become numeric in TS and named in Swift', () => {
    expect(out.ts).toContain('"fontWeight": "400"');
    expect(out.swift).toContain('font: .system(.body, weight: .regular)');
  });
});

describe('validation names the broken token', () => {
  const broken = (mutate: (t: any) => void) => {
    const t: any = tiny();
    mutate(t);
    return () => gen.generate(JSON.stringify(t));
  };
  test('missing dark', () => {
    expect(broken((t) => delete t.color.label.dark)).toThrow('color.label: needs both "light" and "dark"');
  });
  test('unknown weight', () => {
    expect(broken((t) => (t.type.body.weight = 'heavy'))).toThrow('type.body.weight: "heavy" is not one of');
  });
  test('missing group', () => {
    expect(broken((t) => delete t.motion)).toThrow('tokens.json: missing "motion"');
  });
  test('invalid JSON', () => {
    expect(() => gen.generate('{ nope')).toThrow('design/iris/tokens.json: invalid JSON');
  });
});

describe('main', () => {
  function sandbox(tokens: string): string {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'iris-tokens-'));
    fs.mkdirSync(path.join(root, 'design/iris'), { recursive: true });
    fs.writeFileSync(path.join(root, gen.SOURCE), tokens);
    return root;
  }
  const quiet = () => {
    jest.spyOn(console, 'log').mockImplementation(() => {});
    jest.spyOn(console, 'error').mockImplementation(() => {});
  };
  afterEach(() => jest.restoreAllMocks());

  test('writes all four outputs, then --check passes', () => {
    quiet();
    const root = sandbox(JSON.stringify(tiny()));
    expect(gen.main([], root)).toBe(0);
    for (const rel of Object.values(gen.OUTPUTS)) expect(fs.existsSync(path.join(root, rel))).toBe(true);
    expect(gen.main(['--check'], root)).toBe(0);
  });
  test('--check fails when an output was hand-edited', () => {
    quiet();
    const root = sandbox(JSON.stringify(tiny()));
    gen.main([], root);
    fs.appendFileSync(path.join(root, gen.OUTPUTS.css), '/* edit */');
    expect(gen.main(['--check'], root)).toBe(1);
  });
  test('a broken token set exits 1 and writes nothing', () => {
    quiet();
    const root = sandbox('{ nope');
    expect(gen.main([], root)).toBe(1);
    for (const rel of Object.values(gen.OUTPUTS)) expect(fs.existsSync(path.join(root, rel))).toBe(false);
  });
});

describe('the committed outputs', () => {
  test('match design/iris/tokens.json (run `npm run tokens` if this fails)', () => {
    const root = path.resolve(__dirname, '../..');
    const out = gen.generate(fs.readFileSync(path.join(root, gen.SOURCE), 'utf8'));
    for (const [key, rel] of Object.entries(gen.OUTPUTS)) {
      const file = path.join(root, rel);
      expect({ file: rel, exists: fs.existsSync(file) }).toEqual({ file: rel, exists: true });
      expect({ file: rel, upToDate: fs.readFileSync(file, 'utf8') === out[key as keyof typeof out] }).toEqual({ file: rel, upToDate: true });
    }
  });
});

describe('component reference renderings (I6)', () => {
  const ROOT = path.join(__dirname, '..', '..');
  const VARIANTS = ['light', 'dark', 'ax5'];

  test('COMPONENTS matches the headings in design/iris/components.md', () => {
    const md = fs.readFileSync(path.join(ROOT, 'design/iris/components.md'), 'utf8');
    const headings = md.split('\n').filter((l) => l.startsWith('## Iris')).map((l) => l.slice(3).trim());
    expect(gen.COMPONENTS).toEqual(headings);
  });

  test('every component has committed light, dark and AX5 screenshots', () => {
    const missing = gen.COMPONENTS.flatMap((c) => VARIANTS.map((v) => `docs/design/iris/${c}-${v}.png`)).filter(
      (p) => !fs.existsSync(path.join(ROOT, p)),
    );
    expect(missing).toEqual([]);
  });

  test('iris.html shows every component screenshot', () => {
    const { html } = gen.generate(fs.readFileSync(path.join(ROOT, 'design/iris/tokens.json'), 'utf8'));
    for (const c of gen.COMPONENTS) for (const v of VARIANTS) expect(html).toContain(`iris/${c}-${v}.png`);
    expect(html).not.toContain('Component specimens arrive in I6');
  });
});
