#!/usr/bin/env node
// Iris design tokens (spec §4.1): design/iris/tokens.json → Swift, TS, CSS
// and the docs/design/iris.html specimen. No dependencies.
//   node scripts/iris-tokens.js          write every output
//   node scripts/iris-tokens.js --check  exit 1 if a committed output is stale
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const SOURCE = 'design/iris/tokens.json';
// The components in design/iris/components.md, in order (I6). iris.html shows
// each one's iOS reference screenshots from docs/design/iris/.
const COMPONENTS = [
  'IrisShelfRow', 'IrisCover', 'IrisProgress', 'IrisCategoryChip', 'IrisPrimaryButton',
  'IrisSheet', 'IrisEmptyState', 'IrisRatingBadge', 'IrisComparisonCard', 'IrisSymbol',
];
const SHOT_VARIANTS = { light: 'light appearance', dark: 'dark appearance', ax5: 'accessibility text size 5' };

const OUTPUTS = {
  swift: 'apple/Iris/DesignSystem/IrisTokens.swift',
  ts: 'src/ui/iris/tokens.ts',
  css: 'design/iris/iris.css',
  html: 'docs/design/iris.html',
};
const GROUPS = ['color', 'type', 'space', 'radius', 'motion', 'glass'];
const WEIGHTS = { regular: '400', medium: '500', semibold: '600', bold: '700' };
const HEX = /^#([0-9A-Fa-f]{6})([0-9A-Fa-f]{2})?$/;

function parseColor(value, where) {
  const m = typeof value === 'string' ? HEX.exec(value) : null;
  if (!m) throw new Error(`${where}: "${value}" is not #RRGGBB or #RRGGBBAA`);
  const n = parseInt(m[1], 16);
  const alpha = m[2] === undefined ? 1 : Math.round((parseInt(m[2], 16) / 255) * 1000) / 1000;
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255, alpha, hex: m[1].toUpperCase() };
}

function num(value, where) {
  if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`${where}: must be a number`);
  return value;
}

function pair(t, where) {
  if (!t || t.light === undefined || t.dark === undefined) throw new Error(`${where}: needs both "light" and "dark"`);
  return { light: parseColor(t.light, `${where}.light`), dark: parseColor(t.dark, `${where}.dark`) };
}

function validate(tokens) {
  for (const g of GROUPS) if (!tokens[g]) throw new Error(`tokens.json: missing "${g}"`);
  const colors = {};
  for (const [name, t] of Object.entries(tokens.color)) colors[name] = { ...pair(t, `color.${name}`), ios: t.ios ?? null };
  const type = {};
  for (const [name, t] of Object.entries(tokens.type)) {
    if (!(t.weight in WEIGHTS)) throw new Error(`type.${name}.weight: "${t.weight}" is not one of ${Object.keys(WEIGHTS).join(', ')}`);
    if (typeof t.ios !== 'string') throw new Error(`type.${name}.ios: must name a SwiftUI Font.TextStyle`);
    type[name] = {
      size: num(t.size, `type.${name}.size`),
      lineHeight: num(t.lineHeight, `type.${name}.lineHeight`),
      tracking: num(t.tracking, `type.${name}.tracking`),
      weight: t.weight,
      ios: t.ios,
    };
  }
  const flat = (g) => Object.fromEntries(Object.entries(tokens[g]).map(([k, v]) => [k, num(v, `${g}.${k}`)]));
  const motion = {};
  for (const [name, t] of Object.entries(tokens.motion)) {
    motion[name] = { response: num(t.response, `motion.${name}.response`), damping: num(t.damping, `motion.${name}.damping`) };
  }
  const glass = {};
  for (const [name, t] of Object.entries(tokens.glass)) {
    glass[name] = { blur: num(t.blur, `glass.${name}.blur`), tint: pair(t.tint, `glass.${name}.tint`), border: pair(t.border, `glass.${name}.border`) };
  }
  return { colors, type, space: flat('space'), radius: flat('radius'), motion, glass };
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const css = (c) => (c.alpha === 1 ? `#${c.hex}` : `rgba(${c.r}, ${c.g}, ${c.b}, ${c.alpha})`);
const sw = (c) => `(0x${c.hex}, ${c.alpha === 1 ? '1.0' : c.alpha})`;
const header = (open, close, hash) =>
  `${open} GENERATED by scripts/iris-tokens.js from ${SOURCE} — do not edit; run \`npm run tokens\`.${close}\n` +
  `${open} source-sha256: ${hash}${close}\n`;

function renderSwift(t, hash) {
  const L = [header('//', '', hash), 'import SwiftUI', 'import UIKit', ''];
  L.push('/// Iris design tokens (spec §4.1). Edit design/iris/tokens.json, then `npm run tokens`.');
  L.push('enum IrisTokens {', `    static let sourceSHA256 = "${hash}"`, '');
  L.push('    enum Colors {');
  for (const [n, c] of Object.entries(t.colors)) {
    L.push(c.ios ? `        static let ${n} = Color(uiColor: .${c.ios})` : `        static let ${n} = dynamic(${sw(c.light)}, ${sw(c.dark)})`);
  }
  L.push('    }', '');
  L.push('    struct TextStyle: Sendable {', '        let font: Font', '        let size: CGFloat', '        let lineHeight: CGFloat', '        let tracking: CGFloat', '    }', '');
  L.push('    enum Typography {');
  for (const [n, s] of Object.entries(t.type)) {
    L.push(`        static let ${n} = TextStyle(font: .system(.${s.ios}, weight: .${s.weight}), size: ${s.size}, lineHeight: ${s.lineHeight}, tracking: ${s.tracking})`);
  }
  L.push('    }', '');
  for (const [g, Name] of [['space', 'Space'], ['radius', 'Radius']]) {
    L.push(`    enum ${Name} {`);
    for (const [n, v] of Object.entries(t[g])) L.push(`        static let ${n}: CGFloat = ${v}`);
    L.push('    }', '');
  }
  L.push('    enum Motion {');
  for (const [n, m] of Object.entries(t.motion)) L.push(`        static let ${n} = Animation.spring(response: ${m.response}, dampingFraction: ${m.damping})`);
  L.push('    }', '');
  L.push('    /// Used when Liquid Glass is unavailable or Reduce Transparency is on.');
  L.push('    struct GlassFallback: Sendable {', '        let blur: CGFloat', '        let tint: Color', '        let border: Color', '    }', '');
  L.push('    enum Glass {');
  for (const [n, g] of Object.entries(t.glass)) {
    L.push(`        static let ${n} = GlassFallback(blur: ${g.blur}, tint: dynamic(${sw(g.tint.light)}, ${sw(g.tint.dark)}), border: dynamic(${sw(g.border.light)}, ${sw(g.border.dark)}))`);
  }
  L.push('    }', '}', '');
  L.push('/// A colour that follows the trait collection: light value, dark value.');
  L.push('private func dynamic(_ light: (UInt32, Double), _ dark: (UInt32, Double)) -> Color {');
  L.push('    Color(uiColor: UIColor { traits in');
  L.push('        let (rgb, alpha) = traits.userInterfaceStyle == .dark ? dark : light');
  L.push('        return UIColor(');
  L.push('            red: CGFloat((rgb >> 16) & 0xFF) / 255,');
  L.push('            green: CGFloat((rgb >> 8) & 0xFF) / 255,');
  L.push('            blue: CGFloat(rgb & 0xFF) / 255,');
  L.push('            alpha: alpha');
  L.push('        )');
  L.push('    })');
  L.push('}', '');
  return L.join('\n');
}

function renderTs(t, hash) {
  const scheme = (k) => Object.fromEntries(Object.entries(t.colors).map(([n, c]) => [n, css(c[k])]));
  const type = Object.fromEntries(
    Object.entries(t.type).map(([n, s]) => [n, { fontSize: s.size, lineHeight: s.lineHeight, fontWeight: WEIGHTS[s.weight], letterSpacing: s.tracking }]),
  );
  const glass = Object.fromEntries(
    Object.entries(t.glass).map(([n, g]) => [
      n,
      { blur: g.blur, tint: { light: css(g.tint.light), dark: css(g.tint.dark) }, border: { light: css(g.border.light), dark: css(g.border.dark) } },
    ]),
  );
  const out = (name, value) => `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
  return [
    header('//', '', hash),
    `export const irisSourceSha256 = '${hash}';\n`,
    out('irisColors', { light: scheme('light'), dark: scheme('dark') }),
    out('irisType', type),
    out('irisSpace', t.space),
    out('irisRadius', t.radius),
    out('irisMotion', t.motion),
    out('irisGlass', glass),
  ].join('\n');
}

function renderCss(t, hash) {
  const colors = (k) => Object.entries(t.colors).map(([n, c]) => `  --iris-color-${kebab(n)}: ${css(c[k])};`);
  const glassColors = (k) =>
    Object.entries(t.glass).flatMap(([n, g]) => [
      `  --iris-glass-${kebab(n)}-tint: ${css(g.tint[k])};`,
      `  --iris-glass-${kebab(n)}-border: ${css(g.border[k])};`,
    ]);
  const fixed = [
    '  --iris-font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Inter", system-ui, sans-serif;',
    ...Object.entries(t.type).flatMap(([n, s]) => [
      `  --iris-type-${kebab(n)}-size: ${s.size}px;`,
      `  --iris-type-${kebab(n)}-line-height: ${s.lineHeight}px;`,
      `  --iris-type-${kebab(n)}-weight: ${WEIGHTS[s.weight]};`,
      `  --iris-type-${kebab(n)}-tracking: ${s.tracking}px;`,
    ]),
    ...Object.entries(t.space).map(([n, v]) => `  --iris-space-${kebab(n)}: ${v}px;`),
    ...Object.entries(t.radius).map(([n, v]) => `  --iris-radius-${kebab(n)}: ${v}px;`),
    ...Object.entries(t.glass).map(([n, g]) => `  --iris-glass-${kebab(n)}-blur: ${g.blur}px;`),
  ];
  const typeClasses = Object.keys(t.type).map(
    (n) =>
      `.iris-type-${kebab(n)} { font-family: var(--iris-font-family); font-size: var(--iris-type-${kebab(n)}-size); ` +
      `line-height: var(--iris-type-${kebab(n)}-line-height); font-weight: var(--iris-type-${kebab(n)}-weight); ` +
      `letter-spacing: var(--iris-type-${kebab(n)}-tracking); }`,
  );
  return [
    header('/*', ' */', hash),
    ':root {',
    '  color-scheme: light dark;',
    ...fixed,
    '}',
    '',
    ':root, [data-theme="light"] {',
    ...colors('light'),
    ...glassColors('light'),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    '  :root:not([data-theme="light"]) {',
    ...colors('dark').map((l) => `  ${l}`),
    ...glassColors('dark').map((l) => `  ${l}`),
    '  }',
    '}',
    '',
    '[data-theme="dark"] {',
    ...colors('dark'),
    ...glassColors('dark'),
    '}',
    '',
    ...typeClasses,
    '',
  ].join('\n');
}

function renderHtml(t, hash) {
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const swatches = (theme) =>
    Object.keys(t.colors)
      .map((n) => `<div class="swatch"><span style="background: var(--iris-color-${kebab(n)})"></span><code>${n}</code></div>`)
      .join('\n        ');
  const ramp = Object.entries(t.type)
    .map(([n, s]) => `<p class="iris-type-${kebab(n)}">${esc(n)} <small>${s.size}/${s.lineHeight} · ${s.weight}</small></p>`)
    .join('\n      ');
  const space = Object.entries(t.space)
    .map(([n, v]) => `<div class="row"><code>${n} ${v}</code><i style="width: var(--iris-space-${kebab(n)})"></i></div>`)
    .join('\n      ');
  const radius = Object.entries(t.radius)
    .map(([n, v]) => `<div class="box" style="border-radius: var(--iris-radius-${kebab(n)})"><code>${n} ${v}</code></div>`)
    .join('\n      ');
  const glass = Object.keys(t.glass)
    .map(
      (n) =>
        `<div class="glass" style="backdrop-filter: blur(var(--iris-glass-${kebab(n)}-blur)); -webkit-backdrop-filter: blur(var(--iris-glass-${kebab(n)}-blur)); ` +
        `background: var(--iris-glass-${kebab(n)}-tint); border: 1px solid var(--iris-glass-${kebab(n)}-border)"><code>glass.${n}</code></div>`,
    )
    .join('\n        ');
  const components = COMPONENTS.map(
    (c) => `<figure class="component">
        <figcaption class="iris-type-headline">${c}</figcaption>
        <div class="shots">${Object.entries(SHOT_VARIANTS)
          .map(([v, label]) => `<img src="iris/${c}-${v}.png" alt="${c}, ${label}" loading="lazy">`)
          .join('')}</div>
      </figure>`,
  ).join('\n      ');
  return `<!DOCTYPE html>
${header('<!--', ' -->', hash)}<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Iris Tokens</title>
  <link rel="stylesheet" href="../../design/iris/iris.css">
  <style>
    body { margin: 0; background: var(--iris-color-grouped-background); color: var(--iris-color-label); font-family: var(--iris-font-family); }
    main { max-width: 960px; margin: 0 auto; padding: var(--iris-space-xl) var(--iris-space-lg); }
    section { margin-bottom: var(--iris-space-xxxl); }
    h2 { color: var(--iris-color-secondary-label); }
    .themes { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: var(--iris-space-lg); }
    .panel { background: var(--iris-color-grouped-background); color: var(--iris-color-label); padding: var(--iris-space-lg); border-radius: var(--iris-radius-card); border: 1px solid var(--iris-color-separator); }
    .swatch { display: flex; align-items: center; gap: var(--iris-space-sm); padding: var(--iris-space-xs) 0; }
    .swatch span { width: 36px; height: 36px; border-radius: var(--iris-radius-control); border: 1px solid var(--iris-color-separator); }
    code { font-size: 13px; color: var(--iris-color-secondary-label); }
    small { color: var(--iris-color-tertiary-label); font-size: 12px; }
    p { margin: var(--iris-space-xs) 0; }
    .row { display: flex; align-items: center; gap: var(--iris-space-md); }
    .row code { width: 80px; } .row i { height: 12px; background: var(--iris-color-accent); border-radius: 2px; }
    .boxes { display: flex; flex-wrap: wrap; gap: var(--iris-space-md); }
    .box { width: 120px; height: 80px; background: var(--iris-color-secondary-grouped-background); border: 1px solid var(--iris-color-separator); display: grid; place-items: center; }
    .stage { padding: var(--iris-space-xl); border-radius: var(--iris-radius-card); background: linear-gradient(135deg, var(--iris-color-category-show), var(--iris-color-category-movie), var(--iris-color-category-manga)); display: flex; gap: var(--iris-space-lg); flex-wrap: wrap; }
    .glass { padding: var(--iris-space-lg) var(--iris-space-xl); border-radius: var(--iris-radius-sheet); }
    .component { margin: 0 0 var(--iris-space-xxl); }
    .shots { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: var(--iris-space-md); margin-top: var(--iris-space-sm); }
    .shots img { width: 100%; height: auto; border-radius: var(--iris-radius-card); border: 1px solid var(--iris-color-separator); }
    @media (max-width: 600px) { .shots { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <main>
    <h1 class="iris-type-large-title">Iris tokens</h1>
    <p class="iris-type-subheadline">Generated from <code>${SOURCE}</code>. Components are specified in <code>design/iris/components.md</code>; the renderings at the end are the iOS reference (I6), captured by <code>apple/scripts/screenshots.sh</code>.</p>
    <section>
      <h2 class="iris-type-title3">Colour</h2>
      <div class="themes">
        <div class="panel" data-theme="light">
        ${swatches('light')}
        </div>
        <div class="panel" data-theme="dark">
        ${swatches('dark')}
        </div>
      </div>
    </section>
    <section>
      <h2 class="iris-type-title3">Type</h2>
      ${ramp}
    </section>
    <section>
      <h2 class="iris-type-title3">Space</h2>
      ${space}
    </section>
    <section>
      <h2 class="iris-type-title3">Radius</h2>
      <div class="boxes">
      ${radius}
      </div>
    </section>
    <section>
      <h2 class="iris-type-title3">Glass fallback</h2>
      <div class="themes">
        <div class="stage" data-theme="light">
        ${glass}
        </div>
        <div class="stage" data-theme="dark">
        ${glass}
        </div>
      </div>
    </section>
    <section>
      <h2 class="iris-type-title3">Components — iOS reference</h2>
      ${components}
    </section>
  </main>
</body>
</html>
`;
}

function generate(raw) {
  let tokens;
  try {
    tokens = JSON.parse(raw);
  } catch (e) {
    throw new Error(`${SOURCE}: invalid JSON — ${e.message}`);
  }
  const t = validate(tokens);
  const hash = crypto.createHash('sha256').update(raw).digest('hex');
  return { swift: renderSwift(t, hash), ts: renderTs(t, hash), css: renderCss(t, hash), html: renderHtml(t, hash) };
}

function main(argv, root = ROOT) {
  let out;
  try {
    out = generate(fs.readFileSync(path.join(root, SOURCE), 'utf8'));
  } catch (e) {
    console.error(e.message);
    return 1;
  }
  if (argv.includes('--check')) {
    const stale = Object.values(OUTPUTS).filter((rel, i) => {
      const file = path.join(root, rel);
      return !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== Object.values(out)[i];
    });
    if (stale.length) {
      console.error(`Stale — run \`npm run tokens\`:\n  ${stale.join('\n  ')}`);
      return 1;
    }
    console.log('Iris tokens up to date');
    return 0;
  }
  for (const [key, rel] of Object.entries(OUTPUTS)) {
    const file = path.join(root, rel);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, out[key]);
    console.log(`wrote ${rel}`);
  }
  return 0;
}

module.exports = { generate, parseColor, main, OUTPUTS, SOURCE, COMPONENTS };
if (require.main === module) process.exit(main(process.argv.slice(2)));
