import Foundation
import GRDB
import XCTest
@testable import IrisCore

/// Spec §3: the Swift database must be the TS schema, byte for byte, so a
/// database or backup moves between platforms unchanged.
final class SchemaTests: XCTestCase {
    private static let schemaFile = fixturesDirectory
        .deletingLastPathComponent().appendingPathComponent("schema/schema.sql")

    /// The same text shared/schema/__tests__/schema.test.ts writes.
    private func dump(_ db: Database) throws -> String {
        let version = try Int.fetchOne(db, sql: "SELECT version FROM schema_version") ?? -1
        let sql = try String.fetchAll(db, sql: "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY type, name")
        return [
            "-- GENERATED by shared/schema/__tests__/schema.test.ts (npm run fixtures:record) — do not edit.",
            "-- The schema after every migration in src/db/schema.ts. Iris I4 must reproduce it.",
            "-- schema_version: \(version)",
            "",
            sql.map { jsTrim($0) + ";" }.joined(separator: "\n\n"),
            "",
        ].joined(separator: "\n")
    }

    func testMigratedSchemaIsTheTSSchemaByteForByte() throws {
        let queue = try DatabaseQueue()
        try queue.write { try migrate($0) }
        let actual = try queue.read { try dump($0) }
        XCTAssertEqual(actual, try String(contentsOf: Self.schemaFile, encoding: .utf8))
    }

    func testMigrateIsIdempotent() throws {
        let queue = try DatabaseQueue()
        try queue.write { try migrate($0) }
        try queue.write { try migrate($0) }
        XCTAssertEqual(try queue.read { try Int.fetchOne($0, sql: "SELECT version FROM schema_version") }, migrations.count)
    }

    func testSchemaVersionConstantMatchesTheMigrations() {
        XCTAssertEqual(IrisSchema.version, migrations.count)
    }
}
